<?php

namespace Litalex\Component\Parser;

use Litalex\Component\Parser\Interfaces\ParserProviderInterface;
use Symfony\Component\DomCrawler\Crawler;

/**
 * Class CrawlerProvider.
 */
class CrawlerProvider extends Crawler implements ParserProviderInterface
{
    public function __construct($node = null, $currentUri = null, $baseHref = null)
    {
        parent::__construct($node, $currentUri, $baseHref);
    }

    public function add($node)
    {
        parent::add($node); // TODO: Change the autogenerated stub
    }

    public function attr($attribute)
    {
        return parent::attr($attribute); // TODO: Change the autogenerated stub
    }

    public function text()
    {
        return parent::text(); // TODO: Change the autogenerated stub
    }

    public function html()
    {
        return parent::html(); // TODO: Change the autogenerated stub
    }

    public function filter($selector)
    {
        return parent::filter($selector); // TODO: Change the autogenerated stub
    }
}
