<?php

namespace Litalex\Providers;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        'Litalex\Events\SomeEvent' => [
            'Litalex\Listeners\EventListener',
        ],
    ];

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

}

